services:
  api_container:
    container_name: api_container
    build:
      context: .
      dockerfile: tmp.dockerfile
    tty: true
    restart: always
    volumes:
      - .:/app
    ports:
      - 8080:5291
    depends_on:
      postgresql:
        condition: service_healthy
  postgresql:
    container_name: postgresql_container
    build:
      context: database
      dockerfile: dockerfile
    tty: true
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: example
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U example"]
      interval: 1s
      timeout: 5s
      retries: 10

volumes:
  pgdata: {}
